### PR TITLE
Issue#39

### PR DESCRIPTION
**Pull request by beribak**
buttons text replaced with icons and buttonBar moved inside videoBox

### CODE REVIEW

**Comment by ddfridley** [comment]
The buttons look great.

When the speaker changes, it looks like the buttons jump to the left and then slide to the right to be in the speaker window at the end of the transition.  

Instead, can we either leave the buttons in the same spot and the speakers rotate under them, or can we turn the buttons off and turn them back on after the new speaker is in position.

I see that you have the svg icons  in  undebate.jsx .  It's great that the browser doesn't have to fetch them individually at run time.   But I also see stuff in assets.  If you don't need them in assets can you remove them from the repo.  Or maybe I missed something.   -- Sometime lets talk about ways to move 'buttons' into a separate component in a future iteration. 

Thanks. It's great to be working with you on this.

**Comment by ddfridley** [comment]
I edited my comment above  - it seems okay to keep the svg files in assets - it doesn't effect performance and there are more files there than are in undebate.jsx.

**Comment by beribak** [comment]
My reasoning was to contain it inside the videoBox but that makes it slide into view when the box changes from nextUp to speaker. Ill fix that and push the changes by tomorrow.

**Comment by ddfridley** [comment]
Okay, sorry, on more time.  When the viewport is a little wider than square, the buttons render lower, obscuring the candidate name.

image

Also, because were making one more change, I noticed that when the viewport is very wide, it is leaving more space at the left edge, than when it is a little wide.   Lets move the video windows to the left so they are like the above.

image

So - the 'a little wide' view should have button positions like the 'very wide view', and the 'very wide view' should have the video windows left side like the 'a little wide' view.

Thanks!

**Comment by ddfridley** [comment]
Buttons are now Icons!

**Pull request merged**
