### PR TITLE
PR: QA e2e test environment setup

### LINKED ISSUE #98: QA e2e test environment setup
Opening up this ticket to capture our work on getting started with QA automation testing. 

@ddfridley wrote out a checklist of QA e2e tests which can be found [here](https://docs.google.com/document/d/1hJ6mDjHaL5utPMgE3Za1r7FfrjF3ArRwW7vuUllx-3E/edit)

There are a few things we need to decide before getting started on these though. 

## 1) What automation tool are we going to use? 

As far as I know, there are two major UI test automation tools available right now: **Cypress** and **Selenium**. Selenium is older technology and requires a lot more knowledge, setup, and external tooling to get started. Cypress is newer and has a lot of great batteries-included features like snapshot time travel and easier debugging, but it doesn't have support for testing on as many browsers. 

Cypress used to only support testing on Chrome, but [as of Feb 6](https://www.cypress.io/blog/2020/02/06/introducing-firefox-and-edge-support-in-cypress-4-0/) it also supports Microsoft Edge and Firefox. 

@ddfridley I would prefer to use Cypress over Selenium, as there are a whole host of issues with the underlying Webdriver technology behind Selenium, including the following:

> It's slow
It's async
It's stateless
It's exposed over an HTTP server
It's a lowest common denominator
It's limited in scope and features
There are small inconsistencies
There are various driver bugs

You can read more about Cypress roadmap and why it still only has limited browser support in [this ticket](https://github.com/cypress-io/cypress/issues/310). 

So the question is: can we live without Safari support for now or is that a dealbreaker? 

## 2) Do we want to use a BDD tool to write our tests?

I'm in favor of using **Cucumber** with Gherkin syntax to write out our feature tests. This forces us to use the format of Given/When/Then when writing out our tests, which enforces good testing style and code reuse. There are packages for integrating Cucumber with both Cypress and Selenium, so these decisions are independent. 

As an example, here is a browser test written in Selenium (would be slightly simpler in Cypress)

```
const assert = require('assert');
const webdriver = require('selenium-webdriver');
const browser = new webdriver.Builder()
  .usingServer()
  .withCapabilities({'browserName': 'chrome' })
  .build();

browser.get('http://en.wikipedia.org/wiki/Wiki');
browser.findElements(webdriver.By.css('[href^="/wiki/"]'))
.then(function(links){
  assert.equal(19, links.length); // Made up number
  browser.quit();
});
```

and then here is the same test written in Gherkin. 

```
Given I have opened a Web Browser
When I load the Wikipedia article on "Wiki"
Then I have "19" Wiki Links
```

Which one is easier to read and understand? Definitely the Gherkin syntax. We would then have to define the following steps for the Gherkin to work. 

```
Given('I have opened a Web Browser', function() {});
When('I load the Wikipedia article on {stringInDoubleQuotes}', function() {});
Then('I have {stringInDoubleQuotes} Wiki Links', function() {});
```

where each function would carry out the implementation for that step. Make sense? You can read more [here](https://www.sitepoint.com/bdd-javascript-cucumber-gherkin/).

### PR DESCRIPTION
**Pull request by djbowers**
Closes #98 

This PR is not yet finished, as I still have to finish implementing the remaining step definitions. 

I was hoping to get some early feedback though before I spend too much more time on this. Here is a screenshot of the current test runs. The first test is passing and is actually testing that the video starts playing, which is good. The other two tests I haven't figured out how to do exactly yet. 

Screenshot 2020-03-27 15 10 08

Note that I'm totally open to changing any part of this. Please give me any feedback you have. I have a feeling we might need to tweak the gherkin feature tests themselves as well. 

To run these locally, open up two separate terminal prompts, run `npm run dev` in one and `npm run cypress` in the other. Also make sure to `npm install` first as well.

### CODE REVIEW

**Comment by ddfridley** [comment]
I installed and ran it -- on my PC.  It worked.  (It still surprised me)
I notice that when I did npm run cypress it opened up a window, but then I had to hit run tests.   I hope we can find a way to npm run cypress and-start-tests 
It looks great. 
I can see that I'm going to have to spell things the same way in the .feature files and the .js file. 
VSC is saying market place has tools for .feature files.  Have you tried any?
This looks good to go forward with.  It will help a lot.

**Comment by djbowers** [comment]
@ddfridley yes I am using 

Cucumber (Gherkin) Full Support
alexkrechik.cucumberautocomplete

also what do you think the best way would be to identify which video is the moderator?

To do it for the step `the videos should start to play`, I'm using 
```
  cy.get('video')
    .first()
    .shouldBePlaying()
```
because using `.first()` makes sense for that step, but for `the moderator is finished speaking` I think we need a way to identify which video is the moderator. 

In general, I think we should think about adding in a `data-cy` or `data-test-id` prop to each of our videos and buttons so that we can easily select them. You can see in the image below, we are using the second to last selector style to get our Begin button, but it will be harder for the other buttons and the videos because we can't identify them with text. 

```
  cy.get('button')
    .contains(buttonText)
    .click()
```

Screenshot 2020-03-30 16 22 23

**Comment by ddfridley** [comment]
Can you find an example of a React component, button, or div, that satisfy's the cy.get('[data-cy=submit')  I understand how to do it if it's a .btn.btn-large or a #main

**Comment by djbowers** [comment]
Sorry I thought I had pushed those two commits when I wrote that comment, but apparently they didn't go through. 

Take a look at that and let me know what you think. It might be better if we do `data-cy={participant + '-video'}` just like the key, but you get the idea. 

We could do the same for each of the other videos and the video buttons.

**Comment by djbowers** [comment]
Update Apr 1

**Status of the fix/development**
Still working on implementing the step definitions for the Gherkin tests written previously

**Challenges / roadblocks** 
This is the first time I'm writing e2e tests for videos, so there's a lot that I'm getting familiar with. I wouldn't say I'm stuck yet though. Once we finalize how we are going to select items, I should be able to get more of this finished.

I think a challenge I am going to face is how to properly check that a video has been recorded and uploaded. 

**Expected closure date**
I'd like to close this by next week, I can reduce scope if necessary to do so. 

**Availability** 
Wide open for the next week.

**Comment by djbowers** [comment]
Note: I am just picking this back up today. I have been busy working on a technical assessment for a job I am applying for.

**Comment by djbowers** [comment]
On the topic of using `data-cy` vs `dataCy` or the like, I found a paragraph in the following article:
https://www.geeksforgeeks.org/reactjs-introduction-jsx/

>JSX allows us to use attributes with the HTML elements just like we do with normal HTML. But instead of the normal naming convention of HTML, JSX uses camelcase convention for attributes. For example, class in HTML becomes className in JSX. The main reason behind this is that some of the attribute names in HTML like ‘class’ are reserved keywords in JavaScripts. So, in order to avoid this problem, JSX uses the camel case naming convention for attributes. We can also use custom attributes in JSX. **For custom attributes, the names of such attributes should be prefixed by data-.** In the below example, we have used a custom attribute with name **data-sampleAttribute** for the \<h2> tag.

So it seems to me that the `-` is not an issue because it's JSX, the bigger concern is keywords like `class` that are already reserved. 

So I think I'd like to use `data-testid` that way the naming is not unique to Cypress. We can use these testid's with Jest as well. This selector is one of the top three selectors listed by Cypress: https://docs.cypress.io/guides/core-concepts/test-runner.html#Uniqueness

**Comment by ddfridley** [comment]
I'm all for using "-" given it's the recommended practice. I was just surprised it wasn't a syntax error.

⁣Get BlueMail for Android ​

**Comment by djbowers** [comment]
So I ended up ditching the Gherkin syntax in favor of really nailing down the Cypress first. I feel like that's more important and we can always add the Gherkin on top in the future. 

I spent a lot of time getting the two main tests in the PR right, namely
* clicking on the Begin button should cause the videos to play
* videos should rotate after the moderator finishes speaking

If you find either of them to be flaky at all, please let me know!

I think we should close this PR with that and open a new one for recording/uploading video, because that's going to be a whole new can of worms to get into.

**Comment by djbowers** [comment]
@ddfridley sorry for the delay, but this PR should be ready now to merge in. Let me know if you have any issues running the tests. You can now use `npm run cypress:headless` to run the tests in headless mode.

**Comment by ddfridley** [comment]
There is an issue with the second test, where it's waiting for the moderator video to finish.  The problem is, that I see in my setup, it's waiting for the video to finish downloading, but it never finishes.  This may be showing a problem with the stallWatch function.   But lets check all this in since passing on test is better than not having any tests, and it doesn't create any conflicts and keep improving on it.

**Pull request merged**
