### PR TITLE
Move buttons off video#177

### PR DESCRIPTION
**Pull request by Jack-Pham**

### CODE REVIEW

**Comment by ddfridley** [comment]
@Jack-Pham 

On candidate-conversations.jsx
The lay out needs to be checked at many different aspect rations.  Basically resize the window in a bunch of different ways (ok to refresh after you resize).
Here is the layout for localhost:3011/candidate-conversation-5:
image

Vs what you see at cc.enciv.org/candidate-conversation-5
image

The code for calculateStyles needs to consider a lot of things.  We don't have control over the viewport width/height we get but we need to fill it as best we can.  So, in landscape mode, we either make the speaking window plus the agenda the full width of the viewport (as in above) or if that would render taller than the viewport, we make height of everything fit the height of the viewport.  If the buttons are below the speaking window, the test needs to look at the height of the navbar, the first row, the the speaking window, and the height of the buttons, plus the gaps between.  If it's too tall, everything shrinks.  That's this code:
```
if (calcHeight > height) {
        // if the window is really wide - squish the video height so it still fits
        let heightForVideo = height - navBarHeight - vGap - /*titleHeight -*/ vGap - vGap
        let calcHeightForVideo = seatHeight() + speakingHeight()
        seatWidthRatio = (seatWidthRatio * heightForVideo) / calcHeightForVideo
        speakingWidthRatio = (speakingWidthRatio * heightForVideo) / calcHeightForVideo
      }
```
Can you add the above description as comments in the code to calculateStyles for the next person.

Then there's portrait mode:
image

For portrait mode - maybe we need to ask @tianchili11 or @adelinepetty to make a rendering - but I think the button row show go below the speaking window and above the agenda.  For portrait mode, notice that we make 1 or 2 rows of candidates depending on how many.  You can try /candidate-conversation-2, -3, ... -7 to see how it works.  For portrait mode, we are making when speaking window the full width and the agenda takes up what's left in the bottom.

Also - I remember saying to change it to CandidateConversation2 - but in this context that's not necessary and lets change it back - so it merges unchanged.

**Comment by ddfridley** [comment]
For undebate.jsx at localhost:3011/candidate-conversation-candidate-recorder we have similar sizing to consider:
image

But if I make it a little wider - it looks like this: 
image

Also, in the image above notice that the bottom of some of the button names is getting clipped off.  It seams to be an issue with the height of the button bar box. 

We should also consider portrait mode:
image


We've had two candidate record in portrait mode on Android - it works though hitting the finished speaking button while holding the phone is a bit of a challenge.   Also - we are going to force the candidate to turn the phone into landscape mode at the point where they actually record their video.  But they will be able to turn it into landscape mode during the other parts.

- [ ] We should review with the team whether we want dark black buttons like in the recorder, or gray buttons like in the viewer and have both be the same.  I have a preference but lets see what others think.
- [ ]  The Redo and Finished speaking buttons need to show active and inactive state.  In the current implementation, they are orange when active and gray when inactive.  I chose orange to make them stand out - but we should review the colors. 
- [ ]  @tianchili11  or @adelinepetty The finished speaking button shows a light bulb and a check mark.  I liked the previous idea of a person, with sound waves, and a check mark because it was easier to connect to the words finished speaking.  The current button seams like "finished idea".   Lets discuss words and image on Wednesday. 

- [ ]  Looking at the recorder - with the hangup button, and the change camera / change mic buttons,  I want to review again with the group whether the buttons should be right below the speaking window, or at the bottom of the viewport.

**Comment by Jack-Pham** [comment]
@ddfridley I just made some changes. Can you have a look ?

**Comment by ddfridley** [comment]
This has been running in QA and it's time to merge and move to production.

**Pull request merged**
