### PR TITLE
added a webpack plugin for compression, also deleted the original file…

### PR DESCRIPTION
**Pull request by epg323**
…s after compression

### CODE REVIEW

**Comment by epg323** [comment]
results of compression , it was 3.9 mb before
Screen Shot 2020-05-01 at 8 30 11 AM

**Comment by ddfridley** [comment]
I fetched it and merged it with master - that included the helmet changes.  When I tried it on heroku, you couldn't click on the play button and I got this error:
```
The resource from “https://undebate-qa.herokuapp.com/assets/webpack/main.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
candidate-conversation
Loading failed for the <script> with source “https://undebate-qa.herokuapp.com/assets/webpack/main.js”.
```
I suspect that in app/server/routes/server-react-render.js  main.js to main.js.gz but it might be something else.

**Comment by epg323** [comment]
I see the error you are talking about, i know it was working before rebasing so i will try that first.

**Comment by epg323** [comment]
These are my findings:

1) i get this log on the heroku logger: 
       -----> Pruning devDependencies
       Skipping because NODE_ENV is not 'production'

**Comment by epg323** [comment]
This is what I tried: 
  1) I removed the compression plugin from webpack-prod.config.js and i left the compression plugin in webpack-dev-config.js and it worked.
Screen Shot 2020-05-05 at 7 27 22 PM

**Comment by ddfridley** [comment]
We need to have compression in production. In dev its optional.   To test production NODE_ENV needs to be set to "production".  In heroku dash board go to your app and go to settings then click on reveal config (or something like that) and then edit the value of NODE_ENV.

Locally you can export NODE_ENV=production and then you can npm run postinstall and npm run start

Also please test on multiple browsers. I got better error messages out of FF but it didn't work on chrome either. 




⁣Get BlueMail for Android ​

**Comment by epg323** [comment]
I was able to make it work in production by using the express ion compression package. The only con to this is it does not work locally. There are two options i can come up with:
1) keep the webpack plugin so we can compress files locally
2) get rid of the webpack plugin
Screen Shot 2020-05-05 at 8 29 39 PM

**Comment by ddfridley** [comment]
So in production we do it with express compression and in development we do it with webpack.  But locally I hope we can still test the express ion part by setting the NODE_END to production, and npm run postinstall && npm run start.   I think this would be fine.

**Comment by ddfridley** [comment]
and at 270k it looks much more compressed than the last version.

**Comment by epg323** [comment]
Done, let me know if you run into any bugs.

**Pull request merged**
